#!/usr/bin/env bash
# =============================================================================
#  PUT THE BENCH LAPTOP ON THE WIREGUARD MESH  --  Ubuntu 24.04 / 26.04
# =============================================================================
#
#  WHY
#    Without this, reaching the laptop means SSH to the RHEL9 box and a port
#    forward onward. That works, but it puts RHEL9 in the critical path and
#    breaks whenever the laptop's DHCP lease changes.
#
#    On the mesh the laptop is simply 10.20.30.4, from anywhere the tunnel
#    reaches:
#        ssh anatol@10.20.30.4
#        mstsc /v:10.20.30.4
#
#    This REPLACES the autossh reverse tunnel. WireGuard already does that
#    job — NAT traversal, roaming, reconnect — and does it better.
#
#  MESH LAYOUT
#    10.20.30.1   Node0 hub          (wg.gogoj.cloud:51847)
#    10.20.30.2   RHEL9 lab desktop  (hc18kx2)
#    10.20.30.3   owner's Windows desktop
#    10.20.30.4   this bench laptop  <-- what this script sets up
#
#  TWO STEPS, AND THE SECOND IS ON THE HUB
#    The laptop's private key is generated here and never leaves this
#    machine. Only its PUBLIC key travels. The hub cannot admit a peer it
#    has never heard of, so:
#
#      1. Run this script. It prints the laptop's public key.
#      2. Add that key as a peer on the Node0 hub.
#      3. Run this script again — it re-verifies and reports success.
#
#  RUN IT AS:   bash setup-wireguard.sh
#  (not with sudo — it asks for your password when it needs it)
#
# =============================================================================

set -uo pipefail

# ----------------------------------------------------------------- CONFIG ---
MESH_ADDRESS="10.20.30.4/32"     # this laptop. .3 is the owner's desktop.
MESH_SUBNET="10.20.30.0/24"      # routed through the tunnel; nothing else is
HUB_PUBKEY="YIAsSKdueWguVOk2bS1xyL7D6yx/+TyUMnJA8TawgwM="
HUB_ENDPOINT="wg.gogoj.cloud:51847"
KEEPALIVE=25                     # seconds; required behind NAT
WG_IFACE="wg0"

HUB_IP="10.20.30.1"
LAB_IP="10.20.30.2"              # RHEL9, used only as a reachability check
# -----------------------------------------------------------------------------

c_reset=$'\033[0m'; c_bold=$'\033[1m'
c_red=$'\033[31m'; c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_blu=$'\033[34m'
step(){ printf '\n%s==>%s %s%s%s\n' "$c_blu" "$c_reset" "$c_bold" "$*" "$c_reset"; }
ok(){   printf '  %s[ ok ]%s %s\n' "$c_grn" "$c_reset" "$*"; }
warn(){ printf '  %s[warn]%s %s\n' "$c_yel" "$c_reset" "$*"; }
bad(){  printf '  %s[FAIL]%s %s\n' "$c_red" "$c_reset" "$*"; }

CONF="/etc/wireguard/${WG_IFACE}.conf"

[[ $EUID -ne 0 ]] || { echo "Run this WITHOUT sudo:  bash $0"; exit 1; }
sudo -v || { bad "This account cannot use sudo."; exit 1; }

cat <<'EOF'

  ##################################################################
  #                                                                #
  #   B E N C H   L A P T O P   ->   W I R E G U A R D   M E S H   #
  #                                                                #
  ##################################################################

EOF

# ============================================================== install =====
step "Installing WireGuard"
if command -v wg >/dev/null 2>&1; then
  ok "Already installed ($(wg --version 2>/dev/null | head -1))"
else
  sudo apt-get update -qq
  sudo apt-get install -y wireguard wireguard-tools >/dev/null 2>&1 \
    && ok "Installed wireguard" \
    || { bad "Install failed. Is there internet?"; exit 1; }
fi

# ================================================================ keys ======
step "Keys"

# The private key is generated here and never transmitted. umask 077 means
# it is never briefly world-readable on disk, which a naive redirect would
# allow between creation and chmod.
sudo mkdir -p /etc/wireguard
if sudo test -f "$CONF"; then
  ok "Existing config found at $CONF — keeping the current keypair"
  PRIVKEY="$(sudo sed -n 's/^PrivateKey *= *//p' "$CONF" | head -1)"
  PUBKEY="$(printf '%s' "$PRIVKEY" | wg pubkey)"
else
  PRIVKEY="$( (umask 077; wg genkey) )"
  PUBKEY="$(printf '%s' "$PRIVKEY" | wg pubkey)"
  ok "Generated a new keypair"
fi

# =============================================================== config =====
step "Writing $CONF"

# AllowedIPs is deliberately ONLY the mesh subnet. A default route here
# would push all of the laptop's traffic through the tunnel and could cut
# it off from the lab LAN — including the machine it is meant to control.
sudo tee "$CONF" >/dev/null <<EOF
# RMR bench laptop — WireGuard mesh peer
# Generated by setup-wireguard.sh. Public key: $PUBKEY

[Interface]
PrivateKey = $PRIVKEY
Address = $MESH_ADDRESS

[Peer]
# Node0 hub
PublicKey = $HUB_PUBKEY
AllowedIPs = $MESH_SUBNET
Endpoint = $HUB_ENDPOINT
PersistentKeepalive = $KEEPALIVE
EOF
sudo chmod 600 "$CONF"
ok "Config written, mode 600 (root only)"

# =============================================================== bring up ===
step "Starting the tunnel"

sudo systemctl enable "wg-quick@${WG_IFACE}" >/dev/null 2>&1 \
  && ok "Enabled at boot (survives a power cut with nobody in the room)" \
  || bad "Could not enable wg-quick@${WG_IFACE}"

sudo systemctl restart "wg-quick@${WG_IFACE}" >/dev/null 2>&1
sleep 2
if ip addr show "$WG_IFACE" >/dev/null 2>&1; then
  ok "Interface $WG_IFACE is up: $(ip -4 -o addr show "$WG_IFACE" | awk '{print $4}')"
else
  bad "Interface $WG_IFACE did not come up"
  echo "     journalctl -u wg-quick@${WG_IFACE} -b --no-pager | tail -20"
fi

# ============================================================== verify ======
step "Checking the mesh"

HANDSHAKE="$(sudo wg show "$WG_IFACE" latest-handshakes 2>/dev/null | awk '{print $2}')"
if [[ -n "${HANDSHAKE:-}" && "${HANDSHAKE:-0}" -gt 0 ]]; then
  ok "Handshake with the hub completed"
else
  warn "No handshake yet — expected if the hub does not know this peer"
fi

MESH_OK=0
for target in "$HUB_IP:hub" "$LAB_IP:RHEL9"; do
  ip="${target%%:*}"; label="${target##*:}"
  if ping -c2 -W3 "$ip" >/dev/null 2>&1; then
    ok "$label ($ip) reachable"
    MESH_OK=1
  else
    warn "$label ($ip) NOT reachable"
  fi
done

# =============================================================== report =====
echo
echo "======================================================================"
if [[ "$MESH_OK" == "1" ]]; then
  printf '%s  ON THE MESH%s\n' "$c_grn$c_bold" "$c_reset"
  echo "======================================================================"
  echo
  echo "  From the owner's Windows desktop, with the tunnel active:"
  echo
  echo "      ssh $USER@${MESH_ADDRESS%%/*}"
  echo "      mstsc /v:${MESH_ADDRESS%%/*}"
  echo
  echo "  No jump host, no port forward. The RHEL9 box is no longer in the"
  echo "  path, and a new DHCP lease on the lab LAN changes nothing."
else
  printf '%s  NOT ON THE MESH YET — ONE STEP LEFT%s\n' "$c_yel$c_bold" "$c_reset"
  echo "======================================================================"
  echo
  echo "  This laptop's PUBLIC key:"
  echo
  echo "      $PUBKEY"
  echo
  echo "  Add it as a peer on the Node0 hub:"
  echo
  echo "      [Peer]"
  echo "      # RMR bench laptop"
  echo "      PublicKey = $PUBKEY"
  echo "      AllowedIPs = ${MESH_ADDRESS%%/*}/32"
  echo
  echo "  Then on the hub:   sudo wg syncconf wg0 <(wg-quick strip wg0)"
  echo "  Then run this script again to confirm."
fi
echo "======================================================================"
echo
echo "  Public key (always, for reference): $PUBKEY"
echo "  Config: $CONF   Service: wg-quick@${WG_IFACE}"
echo
echo "  NOTE: reboot once and re-check before anyone leaves the lab. A mesh"
echo "  peer that fails to come up after a reboot needs physical access to"
echo "  fix, which is exactly what this is meant to avoid."
echo
